### PR TITLE
PR to Golden Repo

### PR DESCRIPTION
**Pull request by melvinhernandez**
Thank you for taking a look at this Adnan :)

### CODE REVIEW

**Comment by adnanhemani** [comment]
Just a question - when running cucumber, your test suite stalls and take a while to move past. Is it waiting on an external source for some data?

**Comment by adnanhemani** [comment]
In the top bar, there's still two "Link" tabs. Should not be there unless they do something - in which case they should be appropriately named.

**Comment by adnanhemani** [comment]
Took a quiz, no orgs appeared: Hit "Student Govt" -> "Technology". Was expecting to see OCTO (or something similar), but nothing appeared. What's up with that?

**Review by adnanhemani — CHANGES_REQUESTED** [review]
Left some comments that need addressing.

**Comment by Hekaiyo** [comment]
- Just a question - when running cucumber, your test suite stalls and take a while to move past. Is it waiting on an external source for some data?

Yes; the test was incorrectly stubbed, and has been fixed now. Certain other steps stall slightly, but much less so, because some slight wait is required for capybara to correctly click on a modal element.

- In the top bar, there's still two "Link" tabs. Should not be there unless they do something - in which case they should be appropriately named.

These have been removed.

- Took a quiz, no orgs appeared: Hit "Student Govt" -> "Technology". Was expecting to see OCTO (or something similar), but nothing appeared. What's up with that?

As mentioned in an email, currently the CalLink API is extremely slow, and retrieving all relevant orgs takes around 45 seconds. If you are running on localhost, waiting a while should have it load, but Heroku actually times this out after 30 seconds.

There is no easy solution to this; we have to pull from the database, and we've already filtered as much as possible. There is an option on the API to filter by categories, which would theoretically cut down on the amount of orgs retrieved, and therefore the latency, but 1) it only allows us to specify one category instead of a group and 2) the quiz we were provided only gives us keywords (parts of the actual Category name on the database), which we have to sort on our end.

Unfortunately because of the late nature of the entire API function, we did not run into this problem until very late in development, and it went entirely unforeseen. To be clear, our code is functioning as expected, it is the API that is performing slowly.

**Comment by adnanhemani** [comment]
That's fair, thanks for letting me know!

**Pull request merged**
